version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: task_management_postgres
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  rails_api:
    build: .
    container_name: task_management_rails
    environment:
      DATABASE_HOST: postgres
      DATABASE_NAME: taskdb
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      RAILS_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    command: /app/start.sh

volumes:
  postgres_data:
